# Generated by Django 4.2.7 on 2026-02-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_studentgymstate_confirmation_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade_boundaries', models.JSONField(default=dict)),
                ('paper_structure', models.JSONField(default=dict)),
                ('formula_sheet_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('popularity_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paper_number', models.IntegerField(default=1)),
                ('tier', models.CharField(default='higher', max_length=20)),
                ('total_marks', models.IntegerField(default=80)),
                ('time_allowed_minutes', models.IntegerField(default=90)),
                ('calculator_allowed', models.BooleanField(default=True)),
                ('source_year', models.IntegerField(blank=True, null=True)),
                ('source_series', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.examboard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject')),
            ],
            options={
                'ordering': ['-source_year', '-source_series', 'paper_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='examsettings',
            options={'verbose_name_plural': 'Exam Settings'},
        ),
        migrations.AlterModelOptions(
            name='hysteresisstate',
            options={'verbose_name_plural': 'Hysteresis States'},
        ),
        migrations.AddField(
            model_name='examsettings',
            name='exam_date_confidence',
            field=models.CharField(choices=[('approximate', 'Approximate (month/year)'), ('confirmed', 'Confirmed (exact date)'), ('official', 'Official timetable received')], default='approximate', max_length=20),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='papers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='preferred_session_days',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='timetable_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examsettings',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hysteresisstate',
            name='last_stable_tier',
            field=models.CharField(default='at_risk', max_length=25),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('tier_change', 'Tier Change'), ('inactivity', 'Inactivity Spike'), ('decline', 'Sharp Decline'), ('positive', 'Positive Trend'), ('timezone', 'Time Zone Transition'), ('exam_soon', 'Exam Approaching'), ('mock_complete', 'Mock Exam Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Normal'), (3, 'Low')], default=2),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.AlterField(
            model_name='tierassignment',
            name='tier',
            field=models.CharField(choices=[('on_track', 'On Track'), ('stretch_achievable', 'Stretch But Achievable'), ('at_risk', 'At Risk')], max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='examsettings',
            unique_together={('student', 'subject')},
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('total_marks_available', models.IntegerField()),
                ('marks_achieved', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('predicted_grade', models.IntegerField(blank=True, null=True)),
                ('exam_conditions', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mockexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='examsettings',
            name='exam_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.examboard'),
        ),
        migrations.CreateModel(
            name='StudyMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(choices=[('foundation', 'Foundation Building (12+ weeks out)'), ('consolidation', 'Consolidation (6-12 weeks out)'), ('intensive', 'Intensive Revision (2-6 weeks out)'), ('cram', 'Cram Mode (1-2 weeks out)'), ('exam_week', 'Exam Week (0-7 days)'), ('post_exam', 'Post Exam')], default='foundation', max_length=20)),
                ('mode_changed_at', models.DateTimeField(auto_now=True)),
                ('sessions_per_week', models.IntegerField(default=4)),
                ('minutes_per_session', models.IntegerField(default=45)),
                ('new_content_ratio', models.FloatField(default=0.7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
