# Generated by Django 4.2.7 on 2026-02-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_add_student_exam_date'),
        ('dashboard', '0002_examboard_mockexam_alter_examsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.mockexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mock_exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='MockExamAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_achieved', models.PositiveIntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.mockexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
