# Generated by Django 4.2.7 on 2026-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_mock_exam_question_and_attempt_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hysteresisstate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hysteresisstate',
            name='student',
        ),
        migrations.RemoveField(
            model_name='hysteresisstate',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='studymode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studymode',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studymode',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tierassignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tierassignment',
            name='subject',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('tier_change', 'Tier Change'), ('inactivity', 'Inactivity Spike'), ('decline', 'Sharp Decline'), ('positive', 'Positive Trend'), ('timezone', 'Time Zone Transition'), ('exam_soon', 'Exam Approaching'), ('mock_complete', 'Mock Exam Completed'), ('daily_digest', 'Daily Study Digest')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ExamSettings',
        ),
        migrations.DeleteModel(
            name='HysteresisState',
        ),
        migrations.DeleteModel(
            name='StudyMode',
        ),
        migrations.DeleteModel(
            name='TierAssignment',
        ),
    ]
