# Generated by Django 4.2.7 on 2026-02-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_hysteresisstate_unique_together_and_more'),
        ('learning', '0009_add_flashcard_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('paper_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.examboard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject')),
            ],
            options={
                'ordering': ['-year', 'paper_number'],
                'unique_together': {('subject', 'exam_board', 'year', 'paper_number')},
            },
        ),
    ]
