# Quick test of our child-friendly approach
def demonstrate_child_friendly_math():
    print("🏀 QUADRATIC EQUATIONS: The Basketball Story")
    print()
    print("Hey there, math explorer! 🌟")
    print()
    print("Imagine you're shooting a basketball...")
    print("Watch how it flies: UP, UP, UP... then DOWN, DOWN, DOWN")
    print("That curved path is exactly what a quadratic equation draws!")
    print()
    print("The magic formula: ax² + bx + c = 0")
    print("Think of it like a recipe:")
    print("- 'a' = How curvy the ball's path is")
    print("- 'b' = Which direction you're aiming")  
    print("- 'c' = How tall you are when you throw")
    print()
    print("Let's solve x² + 5x + 6 = 0 together!")
    print("We need two numbers that:")
    print("1. Multiply to make 6")
    print("2. Add to make 5")
    print()
    print("What about 2 and 3?")
    print("2 × 3 = 6 ✓")
    print("2 + 3 = 5 ✓")
    print()
    print("So x = -2 or x = -3")
    print()
    print("🎉 You did it! You're a quadratic detective! 🕵️‍♀️")

if __name__ == "__main__":
    demonstrate_child_friendly_math()