# Generated by Django 5.2.6 on 2025-09-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        ("users", "0002_achievement_alter_student_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTopicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions_attempted", models.PositiveIntegerField(default=0)),
                ("questions_correct", models.PositiveIntegerField(default=0)),
                ("average_difficulty", models.FloatField(default=0.0)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.topic"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "topic")},
            },
        ),
        migrations.CreateModel(
            name="StudentWeakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weakness_type",
                    models.CharField(
                        choices=[
                            ("low_accuracy", "Low Accuracy"),
                            ("slow_speed", "Slow Speed"),
                            ("avoided_topic", "Topic Avoidance"),
                            ("high_difficulty_struggle", "High Difficulty Struggle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Mild"), (2, "Moderate"), (3, "Severe")]
                    ),
                ),
                ("identified_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.topic"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "topic", "weakness_type")},
            },
        ),
    ]
