# Generated by Django 5.2.6 on 2025-09-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_studenttopicperformance_studentweakness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studenttopicperformance",
            name="average_difficulty",
        ),
    ]
