# Generated by Django 5.2.6 on 2025-10-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_studenttopicperformance_average_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrizePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("top_grades", "Top GCSE Grades"),
                            ("most_improved", "Most Improved"),
                            ("subject_champion", "Subject Champion"),
                            ("school_champion", "School Champion"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=50)),
                (
                    "total_prize_pool",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("number_of_winners", models.PositiveIntegerField(default=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("results_announced", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(blank=True, max_length=10)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("rank_national", models.PositiveIntegerField(default=0)),
                ("rank_city", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-total_xp"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(
                blank=True, help_text="City where you live", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school_name",
            field=models.CharField(
                blank=True, help_text="Name of your school", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="GCSEResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("mathematics", "Mathematics"),
                            ("biology", "Biology"),
                            ("chemistry", "Chemistry"),
                            ("physics", "Physics"),
                            ("english_language", "English Language"),
                            ("english_literature", "English Literature"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (9, "Grade 9"),
                            (8, "Grade 8"),
                            (7, "Grade 7"),
                            (6, "Grade 6"),
                            (5, "Grade 5"),
                            (4, "Grade 4"),
                            (3, "Grade 3"),
                            (2, "Grade 2"),
                            (1, "Grade 1"),
                            (0, "U (Ungraded)"),
                        ]
                    ),
                ),
                (
                    "exam_board",
                    models.CharField(
                        choices=[
                            ("aqa", "AQA"),
                            ("edexcel", "Edexcel"),
                            ("ocr", "OCR"),
                            ("wjec", "WJEC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exam_year", models.PositiveIntegerField()),
                (
                    "certificate_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="gcse_certificates/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("eligible_for_prize", models.BooleanField(default=False)),
                ("prize_awarded", models.BooleanField(default=False)),
                (
                    "prize_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcse_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-grade", "-created_at"],
                "unique_together": {("student", "subject", "exam_year")},
            },
        ),
        migrations.CreateModel(
            name="PrizeWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("gift_card", "Gift Card"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("awarded_date", models.DateTimeField(auto_now_add=True)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "prize_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.prizepool",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StudentWeakness",
        ),
    ]
