# Generated by Django 4.2.7 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_prizepool_school_student_city_student_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='xp_requirement',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
