# Generated by Django - seed achievement records
from django.db import migrations


def create_achievements(apps, schema_editor):
    Achievement = apps.get_model('users', 'Achievement')
    achievements = [
        ('First Lesson', 'first_lesson', 'Complete your first lesson', '📚', 0),
        ('10 Correct', 'ten_correct', 'Answer 10 questions correctly', '✅', 0),
        ('7 Day Streak', 'seven_day_streak', 'Maintain a 7-day study streak', '🔥', 0),
        ('50 XP', 'fifty_xp', 'Earn 50 XP', '⭐', 50),
        ('100 XP', 'hundred_xp', 'Earn 100 XP', '🌟', 100),
    ]
    for name, slug, desc, icon, xp in achievements:
        Achievement.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'description': desc, 'icon': icon, 'xp_requirement': xp}
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_achievement_slug'),
    ]

    operations = [
        migrations.RunPython(create_achievements, noop),
    ]
