# Generated by Django 4.2.7 on 2026-02-15 11:42

from django.db import migrations, models
import uuid


def generate_unique_tokens(apps, schema_editor):
    """Generate unique UUID tokens for existing students."""
    Student = apps.get_model('users', 'Student')
    for student in Student.objects.all():
        student.parent_access_token = uuid.uuid4()
        student.save(update_fields=['parent_access_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure token for parent dashboard access'),
        ),
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='parent_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure token for parent dashboard access', unique=True),
        ),
    ]
