# Generated by Django 5.2.14 on 2026-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                help_text="Parent WhatsApp/SMS number in E.164 format, e.g. +447700900123",
                max_length=20,
                null=True,
            ),
        ),
    ]
