# Generated by Django 5.2.6 on 2025-09-09 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("mathematics", "Mathematics"),
                            ("biology", "Biology"),
                            ("chemistry", "Chemistry"),
                            ("physics", "Physics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color_code", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("theory", "Theory & Concepts"),
                            ("worked_example", "Worked Examples"),
                            ("practice", "Practice Questions"),
                            ("exam_technique", "Exam Technique"),
                            ("revision", "Quick Revision"),
                        ],
                        default="theory",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("foundation", "Foundation"),
                            ("higher", "Higher"),
                            ("both", "Both Tiers"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                (
                    "exam_board",
                    models.CharField(
                        choices=[
                            ("aqa", "AQA"),
                            ("edexcel", "Edexcel"),
                            ("ocr", "OCR"),
                            ("wjec", "WJEC"),
                            ("all", "All Exam Boards"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "key_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of key skills"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="learning.lesson"),
                ),
            ],
            options={
                "ordering": ["topic", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("calculation", "Calculation"),
                            ("short_answer", "Short Answer (1-2 marks)"),
                            ("long_answer", "Long Answer (3+ marks)"),
                            ("practical", "Practical/Experiment"),
                            ("graph_analysis", "Graph/Data Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[
                            (1, "Grade 1-3"),
                            (2, "Grade 4-5"),
                            (3, "Grade 6-7"),
                            (4, "Grade 8-9"),
                        ],
                        default=2,
                    ),
                ),
                ("marks_available", models.PositiveIntegerField(default=1)),
                ("correct_answer", models.TextField()),
                (
                    "marking_scheme",
                    models.TextField(blank=True, help_text="How marks are allocated"),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "exam_board",
                    models.CharField(
                        choices=[
                            ("aqa", "AQA"),
                            ("edexcel", "Edexcel"),
                            ("ocr", "OCR"),
                            ("wjec", "WJEC"),
                            ("generic", "Generic/All Boards"),
                        ],
                        default="generic",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Past paper year", null=True
                    ),
                ),
                (
                    "paper_number",
                    models.CharField(
                        blank=True, help_text="Paper 1, 2, etc.", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="learning.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("foundation", "Foundation"),
                            ("higher", "Higher"),
                            ("both", "Both Tiers"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "exam_weight",
                    models.FloatField(
                        default=0.0, help_text="Percentage of GCSE exam (0-100)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="learning.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order", "name"],
                "unique_together": {("subject", "name")},
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="learning.topic",
            ),
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("time_spent", models.PositiveIntegerField(default=0)),
                ("questions_attempted", models.PositiveIntegerField(default=0)),
                ("questions_correct", models.PositiveIntegerField(default=0)),
                ("average_grade", models.FloatField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "lesson")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("topic", "title")},
        ),
    ]
