# Generated by Django 5.2.6 on 2025-10-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(help_text="Ideal answer or keyword list"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, help_text="Extra notes or model answer"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("short_answer", "Short Answer"),
                    ("long_answer", "Long Answer"),
                    ("calculation", "Calculation"),
                    ("practical", "Practical/Experiment"),
                    ("graph_analysis", "Graph/Data Analysis"),
                ],
                default="short_answer",
                max_length=20,
            ),
        ),
    ]
