# Generated by Django 6.0.1 on 2026-01-25 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_question_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('error_type', models.CharField(choices=[('none', 'No Error'), ('conceptual', 'Conceptual Error'), ('procedural', 'Procedural Error'), ('structural', 'Structural / Logic Error'), ('guess', 'Guessing')], default='none', max_length=20)),
                ('time_to_first_action_ms', models.PositiveIntegerField(blank=True, help_text='Time before first interaction (ms)', null=True)),
                ('time_spent_ms', models.PositiveIntegerField(blank=True, help_text='Total time spent on question (ms)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
