# Generated by Django 6.0.1 on 2026-01-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGymState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(max_length=32)),
                ('stable_since', models.DateTimeField(auto_now_add=True)),
                ('confirmation_count', models.PositiveIntegerField(default=1, help_text='How many consecutive confirmations for this mode')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_states', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_states', to='learning.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
