# Generated by Django 6.0.1 on 2026-02-07 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_studentgymstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgymstate',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Session duration in seconds')),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='learning.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='learning.topic')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(help_text='Expected exam date')),
                ('target_grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9')], default=5, help_text='Target GCSE grade (1-9)')),
                ('exam_board', models.CharField(choices=[('aqa', 'AQA'), ('edexcel', 'Edexcel'), ('ocr', 'OCR'), ('wjec', 'WJEC')], default='aqa', max_length=20)),
                ('tier', models.CharField(choices=[('foundation', 'Foundation'), ('higher', 'Higher')], default='higher', max_length=20)),
                ('last_outlook_tier', models.CharField(blank=True, help_text='Last assigned outlook tier for hysteresis', max_length=50, null=True)),
                ('last_tier_change_date', models.DateField(blank=True, help_text='Date of last tier change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to='learning.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
