# Generated by Django 4.2.7 on 2026-02-10 19:29

import json
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def lesson_key_skills_to_json(apps, schema_editor):
    """Convert Lesson.key_skills from text to valid JSON string before AlterField to JSONField. Use raw SQL to avoid loading rows with new schema."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, key_skills FROM learning_lesson")
        for row in cursor.fetchall():
            pk, raw = row[0], row[1] or ''
            if not raw or (isinstance(raw, str) and raw.strip() == ''):
                new_val = '[]'
            else:
                parts = [p.strip() for p in str(raw).split(',') if p.strip()]
                new_val = json.dumps(parts)
            cursor.execute(
                "UPDATE learning_lesson SET key_skills = %s WHERE id = %s",
                [new_val, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_examboard_mockexam_alter_examsettings_options_and_more'),
        ('learning', '0005_alter_studentgymstate_confirmation_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['topic', 'order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['lesson', 'difficulty_level']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam_board',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paper_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='year',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='exam_weight',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tier',
        ),
        migrations.AddField(
            model_name='question',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='specific_exam_boards',
            field=models.ManyToManyField(blank=True, to='dashboard.examboard'),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.examboard'),
        ),
        migrations.AddField(
            model_name='subject',
            name='specification_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='tier',
            field=models.CharField(choices=[('higher', 'Higher Tier'), ('foundation', 'Foundation Tier')], default='higher', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.RunPython(lesson_key_skills_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lesson',
            name='key_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('worked_examples', 'Worked Examples'), ('practice', 'Practice'), ('revision', 'Revision')], default='theory', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marking_scheme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice'), ('calculation', 'Calculation with Working'), ('extended', 'Extended Response')], default='short_answer', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentexamsettings',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_exam_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentexamsettings',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_exam_settings', to='learning.subject'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam_board', 'name', 'tier')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='exam_board',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon',
        ),
    ]
