# Generated by Django 4.2.7 on 2026-02-10 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0006_alter_lesson_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(help_text='Date of this exam paper')),
                ('paper_label', models.CharField(default='Paper 1', help_text='e.g. Paper 1, Paper 2', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dates', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_dates', to='learning.subject')),
            ],
            options={
                'ordering': ['exam_date'],
                'unique_together': {('student', 'subject', 'paper_label')},
            },
        ),
    ]
