# Generated by Django 4.2.7 on 2026-02-14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_add_flashcard_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicStrengthSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("accuracy_rate", models.FloatField(default=0.0)),
                ("recent_accuracy", models.FloatField(default=0.0)),
                ("questions_attempted", models.PositiveIntegerField(default=0)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topic_strength_snapshots", to=settings.AUTH_USER_MODEL)),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="strength_snapshots", to="learning.topic")),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student", "topic", "date")},
            },
        ),
    ]
