# Generated by Django 4.2.7 on 2026-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_add_skill_step_tracking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionstep',
            constraint=models.UniqueConstraint(fields=('question', 'step_order'), name='unique_question_step_order'),
        ),
    ]
