# Generated by Django 4.2.7 on 2026-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_add_questionstep_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskillstate',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('LEARNING', 'LEARNING'), ('IMPROVING', 'IMPROVING'), ('MASTERED', 'MASTERED'), ('MAINTENANCE', 'MAINTENANCE'), ('AT_RISK', 'AT_RISK')], default='NEW', max_length=20),
        ),
    ]
