# Generated by Django 4.2.7 on 2026-03-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_studentskillstate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='created_at',
            new_name='attempted_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='infographic_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_spent_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Total time on question (ms)', null=True),
        ),
    ]
