# Generated by Django 4.2.7 on 2026-04-14 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0014_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flagged for review after repeated wrong answers'),
        ),
        migrations.CreateModel(
            name='StudentFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'flashcard_id'],
                'unique_together': {('student', 'flashcard')},
            },
        ),
    ]
