# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0015_add_needs_review_to_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong', 'Wrong answer'), ('guess', 'Guessed'), ('slow', 'Too slow'), ('hint_used', 'Needed hint'), ('repeated_wrong', 'Repeated wrong answer')], default='wrong', max_length=30)),
                ('wrong_category', models.CharField(blank=True, max_length=50)),
                ('last_student_answer', models.TextField(blank=True)),
                ('remediation_tip', models.TextField(blank=True)),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('correct_retries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retrying', 'Retrying'), ('mastered', 'Mastered'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_bank_items', to='learning.question')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_bank_items', to='learning.skillnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_bank_items', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_bank_items', to='learning.topic')),
            ],
            options={
                'ordering': ['status', '-last_seen_at'],
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StruggleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('wrong_answer', 'Wrong answer'), ('slow_start', 'Slow start'), ('slow_submit', 'Slow submit'), ('hint_request', 'Hint request'), ('stuck_button', 'Stuck button'), ('repeated_wrong', 'Repeated wrong')], max_length=30)),
                ('stuck_point', models.CharField(blank=True, max_length=200)),
                ('mistake_type', models.CharField(blank=True, max_length=50)),
                ('confidence_level', models.CharField(blank=True, max_length=20)),
                ('time_to_first_action_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('time_spent_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('student_answer', models.TextField(blank=True)),
                ('diagnostic_message', models.TextField(blank=True)),
                ('recommended_intervention', models.CharField(choices=[('none', 'None'), ('hint', 'Hint'), ('worked_example', 'Worked example'), ('video', 'Video'), ('retry_easier', 'Retry easier question'), ('retry_similar', 'Retry similar question')], default='none', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struggle_events', to='learning.question')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='struggle_events', to='learning.quizattempt')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='struggle_events', to='learning.skillnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struggle_events', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struggle_events', to='learning.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
