# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_mistake_bank_and_struggle_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_board', models.CharField(blank=True, max_length=30)),
                ('tier', models.CharField(choices=[('foundation', 'Foundation'), ('higher', 'Higher'), ('both', 'Both')], default='both', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=90)),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('intervention_goal', models.CharField(blank=True, help_text='The exact stuck point this video fixes.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_videos', to='learning.skillnode')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_videos', to='learning.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_videos', to='learning.topic')),
            ],
            options={
                'ordering': ['subject__display_name', 'topic__order', 'title'],
            },
        ),
    ]
