# Generated by Django 6.0.4 on 2026-05-28 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_skillvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_rating',
            field=models.FloatField(default=1500.0, help_text='Learned Elo difficulty. Updated on each first-attempt by a student.'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of first-attempts that have updated difficulty_rating. Drives K-factor.'),
        ),
        migrations.CreateModel(
            name='StudentTopicSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rating', models.FloatField(default=1500.0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_skills', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='learning.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'topic'], name='learning_st_student_792a57_idx')],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
