# Generated by Django 5.2.14 on 2026-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0017_skillvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexamsettings",
            name="mastery_gate_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
