# Generated by Django 5.2.14 on 2026-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0018_llm_cache_and_dashboard_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="worked_solution_cache",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="worked_solution_cached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
