# Generated by Django 5.2.14 on 2026-06-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0018_mastery_gate_field"),
        ("learning", "0019_worked_solution_cache"),
    ]

    operations = []
